spring:
  data:
    mongodb:
#      authentication-database: admin
#      username: root
#      password: root
      database: quizit
      port: 27017
      host: localhost
# lub spring.data.mongodb.uri = mongodb://localhost:27017/quizit


logging:
  level:
    pl.kz: info