spring:
  data:
    mongodb:
#      authentication-database: admin
#      username: root
#      password: root
      database: quizit
      port: 27017
      host: localhost

logging:
  level:
    pl.kz: info